#======================================================

server:
  port: 8888

#======================================================

security:
  user:
    name: admin
    password: 123456

#======================================================

debug: true
logging:
  config: classpath:log4j2-dev.xml

#======================================================